### ISSUE TITLE
Wrong seeding particles

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#26]
Particles are created outside the volume of the original mesh. The cube acts as an emitter:
![front](https://user-images.githubusercontent.com/7983249/79062408-cd5a1300-7ca2-11ea-98a0-d091b1ad0212.jpg)
![right](https://user-images.githubusercontent.com/7983249/79062411-d0550380-7ca2-11ea-8c73-50d03931a53d.jpg)
![top](https://user-images.githubusercontent.com/7983249/79062414-d21ec700-7ca2-11ea-877f-26c9bad11508.jpg)

Here is the blend scene:
[test_seeding.zip](https://github.com/taichi-dev/taichi_elements/files/4465959/test_seeding.zip)

This error is reproduced in Windows 10 at this commit: 47396caaeb0cd4c1bb6bb8d829aee50a1496602a

**Comment by yuanming-hu** [comment]
Thanks for reporting this.

The vertical bars look like voxelization leakage, which is relatively easy to fix.

The extra padding is due to the fact that, if half of the voxel resides in the mesh and we have no choice but to include the whole voxel. This is hard to fix, unless we use a higher resolution grid to make it less pronounced.

Btw, I'm getting a Suzanne in your blend file - is this the correct file?

**Comment by PavelBlend** [comment]
This is not a valid file. I messed up the files. And accidentally deleted the file in which the error was reproduced. I will now try to create a new file.

**Comment by PavelBlend** [comment]
I simulated a voxels_grid object that represents a 32x32x32 voxel grid.
![Screenshot_1](https://user-images.githubusercontent.com/7983249/79071538-0024fb00-7ce5-11ea-92dc-d04672d2ba2d.jpg)

The emitter does not extend beyond the voxels, but the particles are seeded too much. Maybe there is a rounding error?
[seeding_bug.zip](https://github.com/taichi-dev/taichi_elements/files/4466490/seeding_bug.zip)
