### ISSUE TITLE
Sparse Grid MPM Solver

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi_elements#3]
Taichi supports sparse grids and this should be used in the MPM solver to make the simulation domain unbounded. The user will only need to input `dx` (grid cell size) to the MPM solver node.

**Comment by yuanming-hu** [comment]
This will be supported in a few days after https://github.com/taichi-dev/taichi/issues/328 is done.

**Comment by PavelBlend** [comment]
Hello, @yuanming-hu 

Is the Sparse Grid what is shown in this video (4:15 - 5:03)?
https://youtu.be/hpDxWuBN3N4?t=255

If yes, then it turns out that empty areas of the domain will not load the system? And will not require memory?

**Comment by yuanming-hu** [comment]
> Is the Sparse Grid what is shown in this video (4:15 - 5:03)?

Yes

> If yes, then it turns out that empty areas of the domain will not load the system? And will not require memory?



Exactly! I still need sometime to implement & optimize this though.

**Comment by PavelBlend** [comment]
I think you can prioritize issues. I will add priority0, priority1, priority2 labels so that it is possible to highlight the most important issues and highlight those that can be implemented in the future and they are not so critical.

I think this feature is very cool and technologically advanced. And before, I thought that only developers of leading 3D applications can implement this. But I think that for now this function can be postponed until we have closed more basic things.

Labels will mean the following:
priority0 - high priority
priority1 - medium priority
priority3 - low priority

**Comment by yuanming-hu** [comment]
This is done in the latest commit.
