### ISSUE TITLE
AttributeError: 'NodeSocket' object has no attribute 'text'

### ISSUE THREAD

**Issue by matyklug18** [taichi-dev/taichi_elements#46]
when trying to simulate. i am on windows rn, and i am gonna later test on linux(ubuntu 19.10 and manjaro)

**Comment by PavelBlend** [comment]
Can you give me a blend scene in which this error is reproduced?
And tell me the version of the blender and which taichi_elements addon commit you use.

**Comment by matyklug18** [comment]
the example scene 01(blender_demo_01), blender 2.82, and i downloaded elements about 20 mins ago.

**Comment by PavelBlend** [comment]
The fact is that these examples become obsolete as code is added and changed. For these examples to work, you need to download the addon from this commit:
https://github.com/taichi-dev/taichi_elements/tree/5b321b29bf6ee640669c423cbe6f3cad7175c837

After the first release, I will update all the examples. Since backward compatibility was lost in the last commit of the addon. To run these examples, try downloading and installing the addon from the commit I gave above.

**Comment by matyklug18** [comment]
oh, and is the latest commit functional? i can try doing it myself, if i would find out how it works.

**Comment by PavelBlend** [comment]
Yes, the last commit should work. If it will not work for you, then let me know. I can now prepare a scene that will work on the last commit. The scene will be simple. I just would like you to check it on your system.

[elements_example_01.zip](https://github.com/taichi-dev/taichi_elements/files/4496657/elements_example_01.zip)

This scene should work on this commit:
https://github.com/taichi-dev/taichi_elements/tree/d1848fdecd1318e16e31dcf6ba70921bec1f574f

**Comment by matyklug18** [comment]
seems like that worked, thanks!
